# Generated by Django 3.1.2 on 2020-10-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.BigIntegerField(blank=True, db_column='BillNO')),
                ('number_4digit', models.BigIntegerField(blank=True, db_column='4Digit', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('hscode', models.BigIntegerField(blank=True, db_column='HSCode', null=True)),
                ('product', models.TextField(blank=True, db_column='Product', null=True)),
                ('quantity', models.FloatField(blank=True, db_column='Quantity', null=True)),
                ('unit', models.TextField(blank=True, db_column='Unit', null=True)),
                ('item_rate_inv', models.FloatField(blank=True, db_column='Item_Rate_INV', null=True)),
                ('currency', models.TextField(blank=True, db_column='Currency', null=True)),
                ('total_amount_inv_fc', models.FloatField(blank=True, db_column='Total_Amount_INV_FC', null=True)),
                ('fob_inr', models.FloatField(blank=True, db_column='FOB INR', null=True)),
                ('foreignport', models.TextField(blank=True, db_column='ForeignPort', null=True)),
                ('foreigncountry', models.TextField(blank=True, db_column='ForeignCountry', null=True)),
                ('indianport', models.TextField(blank=True, db_column='IndianPort', null=True)),
                ('iec', models.BigIntegerField(blank=True, db_column='IEC', null=True)),
                ('indiancompany', models.TextField(blank=True, db_column='IndianCompany', null=True)),
                ('address1', models.TextField(blank=True, db_column='Address1', null=True)),
                ('address2', models.FloatField(blank=True, db_column='Address2', null=True)),
                ('city', models.TextField(blank=True, db_column='City', null=True)),
                ('foreigncompany', models.TextField(blank=True, db_column='ForeignCompany', null=True)),
                ('invoice_no', models.TextField(blank=True, db_column='Invoice_No', null=True)),
                ('cush', models.TextField(blank=True, db_column='CUSH', null=True)),
                ('iec_pin', models.TextField(blank=True, db_column='IEC_PIN', null=True)),
                ('item_no', models.BigIntegerField(blank=True, db_column='Item_No', null=True)),
                ('item_rate_inr', models.FloatField(blank=True, db_column='Item_Rate_INR', null=True)),
            ],
            options={
                'db_table': 'export',
                'managed': False,
            },
        ),
    ]
